In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [ ]:
pip install numpy

Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (1.26.4)

In [ ]:
pip install datetime

Collecting datetime
  Downloading DateTime-5.5-py3-none-any.whl.metadata (33 kB)
Collecting zope.interface (from datetime)
  Downloading zope.interface-7.1.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.1/44.1 kB 3.1 MB/s eta 0:00:00
Requirement already satisfied: pytz in /usr/local/lib/python3.10/dist-packages (from datetime) (2024.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from zope.interface->datetime) (75.1.0)
Downloading DateTime-5.5-py3-none-any.whl (52 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.6/52.6 kB 4.2 MB/s eta 0:00:00
Downloading zope.interface-7.1.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (254 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 254.2/254.2 kB 9.6 MB/s eta 0:00:00
Installing collected packages: zope.interface, datetime
Successfully installed datetime-5.5 zope.interface-7.1.1

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
import datetime as dt

In [ ]:
import os
os.getcwd()

'/content'

## **Import data dari CSV ke DataFrame**

In [ ]:
df = pd.read_csv('Online Retail Data.csv', header=0)

In [ ]:
df

,order_id,product_code,product_name,quantity,order_date,price,customer_id
0,493410,TEST001,This is a test product.,5,2010-01-04 09:24:00,4.50,12346.0
1,C493411,21539,RETRO SPOTS BUTTER DISH,-1,2010-01-04 09:43:00,4.25,14590.0
2,493412,TEST001,This is a test product.,5,2010-01-04 09:53:00,4.50,12346.0
3,493413,21724,PANDA AND BUNNIES STICKER SHEET,1,2010-01-04 09:54:00,0.85,NaN
4,493413,84578,ELEPHANT TOY WITH BLUE T-SHIRT,1,2010-01-04 09:54:00,3.75,NaN
...,...,...,...,...,...,...,...
461768,539991,21618,4 WILDFLOWER BOTANICAL CANDLES,1,2010-12-23 16:49:00,1.25,NaN
461769,539991,72741,GRAND CHOCOLATECANDLE,4,2010-12-23 16:49:00,1.45,NaN
461770,539992,21470,FLOWER VINE RAFFIA FOOD COVER,1,2010-12-23 17:41:00,3.75,NaN
461771,539992,22258,FELT FARM ANIMAL RABBIT,1,2010-12-23 17:41:00,1.25,NaN
461772,539992,21155,RED RETROSPOT PEG BAG,1,2010-12-23 17:41:00,2.10,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 461773 entries, 0 to 461772
Data columns (total 7 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      461773 non-null  object
 1   product_code  461773 non-null  object
 2   product_name  459055 non-null  object
 3   quantity      461773 non-null  int64
 4   order_date    461773 non-null  object
 5   price         461773 non-null  float64
 6   customer_id   360853 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 24.7+ MB

## Data **Cleansing**

In [ ]:
df_clean = df.copy()

In [ ]:
# Membuat kolom date
df_clean['date'] = pd.to_datetime(df_clean['order_date']).dt.date.astype('datetime64[ns]')

In [ ]:
# Menghapus semua baris tanpa customer_id
df_clean = df_clean[~df_clean['customer_id'].isna()]

In [ ]:
# Menghapus semua baris tanpa product_name
df_clean = df_clean[~df_clean['product_name'].isna()]

In [ ]:
# Membuat semua product_name berhuruf kecil
df_clean = df_clean[(~df_clean['product_code'].str.lower().str.contains('test')) | (~df_clean['product_name'].str.contains('test '))]

In [ ]:
# Membuat kolom order_status dengan nilai 'cancelled' jika order_id diawali dengan huruf 'c' dan 'delivered' jika order_id tanpa awalan huruf 'c'
df_clean['order_status'] = np.where(df_clean['order_id'].str[:1] == 'C', 'cancelled', 'delivered')

In [ ]:
# Mengubah nilai quantity yang negatif menjadi positif kerena nilai negatif tersebut hanya menandakan order tersebut cancelled
df_clean['quantity'] = df_clean['quantity'].abs()

In [ ]:
# Menghapus baris dengan price bernilai negatif
df_clean = df_clean[df_clean['price']>0]

In [ ]:
# Membuat nilai amount, yaitu perkalian antara quantuty dan price
df_clean['amount'] = df_clean['quantity'] * df_clean['price']

<ipython-input-19-e557ac09ae2e>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['amount'] = df_clean['quantity'] * df_clean['price']

In [ ]:
# Mengganti product_name dari product_code yang memiliki beberapa product_name dengan salah satu product_name-nya yang paling sering muncul
most_freq_product_name = df_clean.groupby(['product_code', 'product_name'], as_index = False).agg(order_cnt = ('order_id', 'nunique')).sort_values(['product_code', 'order_cnt'], ascending = [True, False])

In [ ]:
most_freq_product_name['rank'] = most_freq_product_name.groupby('product_code')['order_cnt'].rank(method = 'first', ascending = False)

In [ ]:
most_freq_product_name = most_freq_product_name[most_freq_product_name['rank'] == 1].drop(columns = ['order_cnt', 'rank'])

In [ ]:
df_clean =  df_clean.merge(most_freq_product_name.rename(columns = {'product_name' : 'most_freq_product_name'}), how = 'left', on = 'product_code')

In [ ]:
df_clean['product_name'] = df_clean['most_freq_product_name']

In [ ]:
df_clean = df_clean.drop(columns = 'most_freq_product_name')

In [ ]:
# Mengkonversi customer_id menjadi string
df_clean['customer_id'] = df_clean['customer_id'].astype(str)

In [ ]:
# Menghapus outlier
from scipy import stats

In [ ]:
df_clean = df_clean[(np.abs(stats.zscore(df_clean[['quantity', 'amount']]))<3).all(axis = 1)]

In [ ]:
df_clean = df_clean.reset_index(drop = True)

In [ ]:
df_clean

,order_id,product_code,product_name,quantity,order_date,price,customer_id,date,order_status,amount
0,C493411,21539,RED RETROSPOT BUTTER DISH,1,2010-01-04 09:43:00,4.25,14590.0,2010-01-04,cancelled,4.25
1,493414,21844,RED RETROSPOT MUG,36,2010-01-04 10:28:00,2.55,14590.0,2010-01-04,delivered,91.80
2,493414,21533,RETRO SPOT LARGE MILK JUG,12,2010-01-04 10:28:00,4.25,14590.0,2010-01-04,delivered,51.00
3,493414,37508,NEW ENGLAND CERAMIC CAKE SERVER,2,2010-01-04 10:28:00,2.55,14590.0,2010-01-04,delivered,5.10
4,493414,35001G,HAND OPEN SHAPE GOLD,2,2010-01-04 10:28:00,4.25,14590.0,2010-01-04,delivered,8.50
...,...,...,...,...,...,...,...,...,...,...
358464,539988,84380,SET OF 3 BUTTERFLY COOKIE CUTTERS,1,2010-12-23 16:06:00,1.25,18116.0,2010-12-23,delivered,1.25
358465,539988,84849D,HOT BATHS SOAP HOLDER,1,2010-12-23 16:06:00,1.69,18116.0,2010-12-23,delivered,1.69
358466,539988,84849B,FAIRY SOAP SOAP HOLDER,1,2010-12-23 16:06:00,1.69,18116.0,2010-12-23,delivered,1.69
358467,539988,22854,CREAM SWEETHEART EGG HOLDER,2,2010-12-23 16:06:00,4.95,18116.0,2010-12-23,delivered,9.90
358468,539988,47559B,TEA TIME OVEN GLOVE,2,2010-12-23 16:06:00,1.25,18116.0,2010-12-23,delivered,2.50

In [ ]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 358469 entries, 0 to 358468
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      358469 non-null  object
 1   product_code  358469 non-null  object
 2   product_name  358469 non-null  object
 3   quantity      358469 non-null  int64
 4   order_date    358469 non-null  object
 5   price         358469 non-null  float64
 6   customer_id   358469 non-null  object
 7   date          358469 non-null  datetime64[ns]
 8   order_status  358469 non-null  object
 9   amount        358469 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(6)
memory usage: 27.3+ MB

## **Membuat RFM Segmentation**


*   Agregat data transaksi ke bentuk summary total transaksi (Order), total nilai order(order value), tanggal order terakhir dari setiap pengguna

In [ ]:
df_user = df_clean.groupby('customer_id', as_index = False).agg(order_cnt = ('order_id', 'nunique'), max_order_date = ('date', 'max'), total_order_value = ('amount', 'sum'))

In [ ]:
df_user

     customer_id  order_cnt max_order_date  total_order_value
0        12346.0          5     2010-10-04             602.40
1        12608.0          1     2010-10-31             415.79
2        12745.0          2     2010-08-10             723.85
3        12746.0          2     2010-06-30             266.35
4        12747.0         19     2010-12-13            4094.79
...          ...        ...            ...                ...
3884     18283.0          6     2010-11-22             641.77
3885     18284.0          2     2010-10-06             486.68
3886     18285.0          1     2010-02-17             427.00
3887     18286.0          2     2010-08-20             941.48
3888     18287.0          4     2010-11-22            2345.71

[3889 rows x 4 columns]

## **Buat kolom jumlah hari sejak order terakhir**

In [ ]:
today = df_clean['date'].max()

In [ ]:
df_user['day_since_last_order'] = (today - df_user['max_order_date']).dt.days

In [ ]:
df_user

,customer_id,order_cnt,max_order_date,total_order_value,day_since_last_order
0,12346.0,5,2010-10-04,602.40,80
1,12608.0,1,2010-10-31,415.79,53
2,12745.0,2,2010-08-10,723.85,135
3,12746.0,2,2010-06-30,266.35,176
4,12747.0,19,2010-12-13,4094.79,10
...,...,...,...,...,...
3884,18283.0,6,2010-11-22,641.77,31
3885,18284.0,2,2010-10-06,486.68,78
3886,18285.0,1,2010-02-17,427.00,309
3887,18286.0,2,2010-08-20,941.48,125
3888,18287.0,4,2010-11-22,2345.71,31

In [ ]:
df_user.describe()

,order_cnt,max_order_date,total_order_value,day_since_last_order
count,3889.000000,3889,3889.000000,3889.000000
mean,5.128568,2010-09-23 04:46:57.793777664,1544.623084,90.800720
min,1.000000,2010-01-05 00:00:00,1.250000,0.000000
25%,1.000000,2010-08-19 00:00:00,296.360000,25.000000
50%,3.000000,2010-10-26 00:00:00,648.200000,58.000000
75%,6.000000,2010-11-28 00:00:00,1585.940000,126.000000
max,163.000000,2010-12-23 00:00:00,71970.390000,352.000000
std,8.499330,NaN,3434.816315,88.873286

Buat binning dari jumlah hari sejak order terakhir yang terdiri dari 5 bins dengan batas-batasnya merupakan min, P20, P40, P60, P30, max dan beri label 1 sampai 5 dari bin tertinggi ke terendah sebagai skor recency

In [ ]:
df_user['recency_score'] = pd.cut(df_user['day_since_last_order'],
                                  bins = [df_user['day_since_last_order'].min(),
                                          np.percentile(df_user['day_since_last_order'], 20),
                                          np.percentile(df_user['day_since_last_order'], 40),
                                          np.percentile(df_user['day_since_last_order'], 60),
                                          np.percentile(df_user['day_since_last_order'], 80),
                                          df_user['day_since_last_order'].max()],
                                  labels = [5, 4, 3, 2, 1],
                                  include_lowest = True).astype(int)

In [ ]:
df_user

,customer_id,order_cnt,max_order_date,total_order_value,day_since_last_order,recency_score
0,12346.0,5,2010-10-04,602.40,80,2
1,12608.0,1,2010-10-31,415.79,53,3
2,12745.0,2,2010-08-10,723.85,135,2
3,12746.0,2,2010-06-30,266.35,176,1
4,12747.0,19,2010-12-13,4094.79,10,5
...,...,...,...,...,...,...
3884,18283.0,6,2010-11-22,641.77,31,4
3885,18284.0,2,2010-10-06,486.68,78,2
3886,18285.0,1,2010-02-17,427.00,309,1
3887,18286.0,2,2010-08-20,941.48,125,2
3888,18287.0,4,2010-11-22,2345.71,31,4

In [ ]:
df_user.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3889 entries, 0 to 3888
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           3889 non-null   object
 1   order_cnt             3889 non-null   int64
 2   max_order_date        3889 non-null   datetime64[ns]
 3   total_order_value     3889 non-null   float64
 4   day_since_last_order  3889 non-null   int64
 5   recency_score         3889 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(1)
memory usage: 182.4+ KB

Buat binning dari total transaksi (Order) yang terdiri dari 5 bins dengan batas-batasanya merupakan min, P20, P40, P60, P80, max dan beri label 1 sampai 5 dari bin terendah ke tertinggi sebagai skor frequency

In [ ]:
df_user['frequency_score'] = pd.cut(df_user['order_cnt'],
                                  bins = [0,
                                          np.percentile(df_user['order_cnt'], 20),
                                          np.percentile(df_user['order_cnt'], 40),
                                          np.percentile(df_user['order_cnt'], 60),
                                          np.percentile(df_user['order_cnt'], 80),
                                          df_user['order_cnt'].max()],
                                  labels = [1, 2, 3, 4, 5],
                                  include_lowest = True).astype(int)

In [ ]:
df_user

,customer_id,order_cnt,max_order_date,total_order_value,day_since_last_order,recency_score,frequency_score
0,12346.0,5,2010-10-04,602.40,80,2,4
1,12608.0,1,2010-10-31,415.79,53,3,1
2,12745.0,2,2010-08-10,723.85,135,2,2
3,12746.0,2,2010-06-30,266.35,176,1,2
4,12747.0,19,2010-12-13,4094.79,10,5,5
...,...,...,...,...,...,...,...
3884,18283.0,6,2010-11-22,641.77,31,4,4
3885,18284.0,2,2010-10-06,486.68,78,2,2
3886,18285.0,1,2010-02-17,427.00,309,1,1
3887,18286.0,2,2010-08-20,941.48,125,2,2
3888,18287.0,4,2010-11-22,2345.71,31,4,3

In [ ]:
df_user.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3889 entries, 0 to 3888
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           3889 non-null   object
 1   order_cnt             3889 non-null   int64
 2   max_order_date        3889 non-null   datetime64[ns]
 3   total_order_value     3889 non-null   float64
 4   day_since_last_order  3889 non-null   int64
 5   recency_score         3889 non-null   int64
 6   frequency_score       3889 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(4), object(1)
memory usage: 212.8+ KB

Buat binning dari total nilai order (order value) yang terdiri dari 5 bins dengan batas-batasnya merupakan min, P20, P40, P60, P80, max dan beri label 1 sampai 5 dari bin terendah ke tertinggi sebagai skor monetary

In [ ]:
df_user['monetary_score'] = pd.cut(df_user['total_order_value'],
                                  bins = [df_user['total_order_value'].min(),
                                          np.percentile(df_user['total_order_value'], 20),
                                          np.percentile(df_user['total_order_value'], 40),
                                          np.percentile(df_user['total_order_value'], 60),
                                          np.percentile(df_user['total_order_value'], 80),
                                          df_user['total_order_value'].max()],
                                  labels = [1, 2, 3, 4, 5],
                                  include_lowest = True).astype(int)

In [ ]:
df_user

,customer_id,order_cnt,max_order_date,total_order_value,day_since_last_order,recency_score,frequency_score,monetary_score
0,12346.0,5,2010-10-04,602.40,80,2,4,3
1,12608.0,1,2010-10-31,415.79,53,3,1,2
2,12745.0,2,2010-08-10,723.85,135,2,2,3
3,12746.0,2,2010-06-30,266.35,176,1,2,2
4,12747.0,19,2010-12-13,4094.79,10,5,5,5
...,...,...,...,...,...,...,...,...
3884,18283.0,6,2010-11-22,641.77,31,4,4,3
3885,18284.0,2,2010-10-06,486.68,78,2,2,3
3886,18285.0,1,2010-02-17,427.00,309,1,1,2
3887,18286.0,2,2010-08-20,941.48,125,2,2,4
3888,18287.0,4,2010-11-22,2345.71,31,4,3,5

In [ ]:
df_user.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3889 entries, 0 to 3888
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           3889 non-null   object
 1   order_cnt             3889 non-null   int64
 2   max_order_date        3889 non-null   datetime64[ns]
 3   total_order_value     3889 non-null   float64
 4   day_since_last_order  3889 non-null   int64
 5   recency_score         3889 non-null   int64
 6   frequency_score       3889 non-null   int64
 7   monetary_score        3889 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(5), object(1)
memory usage: 243.2+ KB

## **Buat kolom nama segmen berdasarkan skor recency dan frequency**

In [ ]:
df_user['segment'] = np.select(
    [(df_user['recency_score'] == 5) & (df_user['frequency_score'] > 4),
     (df_user['recency_score'].between(3, 4)) & (df_user['frequency_score'] >= 4),
     (df_user['recency_score'] >= 4) & (df_user['frequency_score'].between(2, 3)),
     (df_user['recency_score'] <= 2) & (df_user['frequency_score'] == 5),
     (df_user['recency_score'] == 3) & (df_user['frequency_score'] == 3),
     (df_user['recency_score'] == 5) & (df_user['frequency_score'] == 1),
     (df_user['recency_score'] == 4) & (df_user['frequency_score'] == 1),
     (df_user['recency_score'] <= 2) & (df_user['frequency_score'].between(3, 4)),
     (df_user['recency_score'] == 3) & (df_user['frequency_score'] <= 2),
     (df_user['recency_score'] <= 2) & (df_user['frequency_score'] <= 2)],
    ['01-Champion', '02-Loyal Customers', '03-Potential Loyalists', '04-Cant Lose Them', '05-Need Attention', '06-New Customer', '07-Promising', '08-At Risk', '09-About to Sleep', '10-Hibernating']
)

In [ ]:
df_user

,customer_id,order_cnt,max_order_date,total_order_value,day_since_last_order,recency_score,frequency_score,monetary_score,segment
0,12346.0,5,2010-10-04,602.40,80,2,4,3,08-At Risk
1,12608.0,1,2010-10-31,415.79,53,3,1,2,09-About to Sleep
2,12745.0,2,2010-08-10,723.85,135,2,2,3,10-Hibernating
3,12746.0,2,2010-06-30,266.35,176,1,2,2,10-Hibernating
4,12747.0,19,2010-12-13,4094.79,10,5,5,5,01-Champion
...,...,...,...,...,...,...,...,...,...
3884,18283.0,6,2010-11-22,641.77,31,4,4,3,02-Loyal Customers
3885,18284.0,2,2010-10-06,486.68,78,2,2,3,10-Hibernating
3886,18285.0,1,2010-02-17,427.00,309,1,1,2,10-Hibernating
3887,18286.0,2,2010-08-20,941.48,125,2,2,4,10-Hibernating
3888,18287.0,4,2010-11-22,2345.71,31,4,3,5,03-Potential Loyalists

In [ ]:
df_user.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3889 entries, 0 to 3888
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           3889 non-null   object
 1   order_cnt             3889 non-null   int64
 2   max_order_date        3889 non-null   datetime64[ns]
 3   total_order_value     3889 non-null   float64
 4   day_since_last_order  3889 non-null   int64
 5   recency_score         3889 non-null   int64
 6   frequency_score       3889 non-null   int64
 7   monetary_score        3889 non-null   int64
 8   segment               3889 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(5), object(2)
memory usage: 273.6+ KB

Tampilkan summary dari RFM Segmentation (point 8) berupa banyaknya pengguna, rata-rata dan medium dari total order, total order value, dan jumlah hari sejak order terakhir

In [ ]:
summary = pd.pivot_table(df_user, index = 'segment', values = ['customer_id', 'day_since_last_order', 'order_cnt', 'total_order_value'],
                         aggfunc = {'customer_id' : pd.Series.nunique, 'day_since_last_order' : [np.mean, np.median], 'order_cnt' : [np.mean, np.median]})

<ipython-input-55-aef593986c26>:1: FutureWarning: The provided callable <function mean at 0x7d49645b55a0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  summary = pd.pivot_table(df_user, index = 'segment', values = ['customer_id', 'day_since_last_order', 'order_cnt', 'total_order_value'],
<ipython-input-55-aef593986c26>:1: FutureWarning: The provided callable <function median at 0x7d4961314ca0> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  summary = pd.pivot_table(df_user, index = 'segment', values = ['customer_id', 'day_since_last_order', 'order_cnt', 'total_order_value'],

In [ ]:
summary['pct_unique'] = (summary['customer_id'] / summary['customer_id'].sum() * 100).round(1)

In [ ]:
summary

                       customer_id day_since_last_order         order_cnt  \
                           nunique                 mean median       mean
segment
0                              165            11.739394   13.0   6.072727
01-Champion                    385            10.137662    9.0  19.493506
02-Loyal Customers             546            40.864469   37.0   8.767399
03-Potential Loyalists         523            23.573614   24.0   2.829828
04-Cant Lose Them               64           121.984375  112.5  11.375000
05-Need Attention              176            58.613636   59.0   3.397727
06-New Customer                 50            14.220000   16.0   1.000000
07-Promising                   142            32.760563   34.0   1.000000
08-At Risk                     426           140.455399  120.0   4.136150
09-About to Sleep              352            58.735795   58.0   1.417614
10-Hibernating                1060           196.837736  199.0   1.313208

                              pct_unique
                       median
segment
0                         6.0        4.2
01-Champion              14.0        9.9
02-Loyal Customers        7.0       14.0
03-Potential Loyalists    3.0       13.4
04-Cant Lose Them         9.5        1.6
05-Need Attention         3.0        4.5
06-New Customer           1.0        1.3
07-Promising              1.0        3.7
08-At Risk                4.0       11.0
09-About to Sleep         1.0        9.1
10-Hibernating            1.0       27.3